Repository Liinkiing/harder-faster-loser, pull requests merged in 2019-01, with the labels that each got.

#20 Feat/base animations
  public/static/assets/sprites/animations.json
  public/static/assets/sprites/pack.json
  public/static/assets/sprites/spam-game/sexy.png
  src/game/manager/AnimationManager.ts
  src/game/objects/Spam.ts
  src/game/scenes/BaseScene.ts
  src/game/scenes/action/SpamGameScene.ts
Labels: dev, enhancement

#22 [DEBUG] Minigame picker
  package.json
  src/assets/styles/components/debug/_game-debug-buttons-toolbar.scss
  src/components/GameDebug.tsx
  src/components/ui/Spacer.tsx
  src/components/ui/Transition.tsx
  src/components/ui/ValidatableInput.tsx
  src/components/ui/debug/DebugContainer.tsx
  src/components/ui/debug/GameDebugButtonsToolbar.tsx
  src/components/ui/debug/GameDebugConfigPanel.tsx
  src/components/ui/debug/GameDebugMinigamePicker.tsx
  src/components/ui/debug/GameDebugStateList.tsx
  src/components/ui/games/RemainingTime.tsx
  src/game/manager/GameManager.ts
  src/game/scenes/BaseScene.ts
  src/game/scenes/DeathscreenScene.ts
  src/game/scenes/PostMinigameScene.ts
  src/store/GameDebugStore.ts
  src/store/GameStore.ts
  src/utils/colors.ts
  src/utils/constants.ts
  src/utils/functions.ts
  src/utils/game.ts
  src/utils/hooks.ts
  src/utils/interfaces.ts
  src/utils/types.ts
  yarn.lock
Labels: dev, enhancement, ui

#24 [FIX] - Minigame picker position
  src/components/Game.tsx
  src/components/GameDebug.tsx
  src/components/ui/debug/DebugContainer.tsx
  src/components/ui/debug/GameDebugConfigPanel.tsx
  src/components/ui/debug/GameDebugMinigamePicker.tsx
  src/components/ui/debug/GameDebugStateList.tsx
  src/utils/interfaces.ts
Labels: dev, fix, refacto, ui

#25 Sandwich game
  public/static/assets/sprites/animations.json
  public/static/assets/sprites/pack.json
  public/static/assets/sprites/sandwich-game/sandwich_flying_585_540.png
  public/static/assets/sprites/sandwich-game/sandwich_plan_building.png
  public/static/assets/sprites/sandwich-game/sandwich_plan_ground.png
  public/static/assets/sprites/sandwich-game/sandwich_plan_landscape.png
  public/static/assets/sprites/sandwich-game/sandwich_plan_sky.png
  public/static/assets/sprites/sandwich-game/sandwich_plan_street-lights.png
  public/static/assets/sprites/sandwich-game/toki_run_255_480.png
  public/static/assets/sprites/sandwich-game/toki_win_390_855.png
  src/assets/styles/modules/_colors.scss
  src/game/scenes/BootScene.ts
  src/game/scenes/MinigameScene.ts
  src/game/scenes/action/SandwichGameScene.ts
  src/game/scenes/action/SpamGameScene.ts
  src/game/scenes/index.ts
  src/utils/constants.ts
  src/utils/enums.ts
  src/utils/game.ts
Labels: dev, enhancement, minigame

#23 [GAME] Password
  public/static/assets/sprites/animations.json
  public/static/assets/sprites/pack.json
  public/static/assets/sprites/password-game/MDP_keyboard_1.png
  public/static/assets/sprites/password-game/MDP_keyboard_1_hover.png
  public/static/assets/sprites/password-game/MDP_keyboard_2.png
  public/static/assets/sprites/password-game/MDP_keyboard_2_hover.png
  public/static/assets/sprites/password-game/MDP_keyboard_3.png
  public/static/assets/sprites/password-game/MDP_keyboard_3_hover.png
  public/static/assets/sprites/password-game/MDP_keyboard_4.png
  public/static/assets/sprites/password-game/MDP_keyboard_4_hover.png
  public/static/assets/sprites/password-game/MDP_keyboard_5.png
  public/static/assets/sprites/password-game/MDP_keyboard_5_hover.png
  public/static/assets/sprites/password-game/MDP_keyboard_6.png
  public/static/assets/sprites/password-game/MDP_keyboard_6_hover.png
  public/static/assets/sprites/password-game/MDP_paw.png
  public/static/assets/sprites/password-game/MDP_screen_1.png
  public/static/assets/sprites/password-game/MDP_screen_2.png
  public/static/assets/sprites/password-game/MDP_star.png
  public/static/assets/sprites/password-game/MDP_symbol_1.png
  public/static/assets/sprites/password-game/MDP_symbol_2.png
  public/static/assets/sprites/password-game/MDP_symbol_3.png
  public/static/assets/sprites/password-game/MDP_symbol_4.png
  public/static/assets/sprites/password-game/MDP_symbol_5.png
  public/static/assets/sprites/password-game/MDP_symbol_6.png
  public/static/assets/sprites/password-game/spritesheets/MDP_Paper_915x1215.png
  public/static/assets/sprites/password-game/spritesheets/MDP_nope_870x975.png
  public/static/assets/sprites/password-game/spritesheets/MDP_valid_870x975.png
  src/components/ui/games/MinigameToolbar.tsx
  src/components/ui/games/RemainingTime.tsx
  src/game/manager/GameManager.ts
  src/game/manager/MinigameManager.ts
  src/game/objects/Spam.ts
  src/game/objects/password-game/ComputerPasswordScreen.ts
  src/game/objects/password-game/KeyboardContainer.ts
  src/game/objects/password-game/KeyboardPasswordButton.ts
  src/game/scenes/BootScene.ts
  src/game/scenes/action/ActionSecondGameScene.ts
  src/game/scenes/action/ActionThirdGameScene.ts
  src/game/scenes/action/PasswordGameScene.ts
  src/game/scenes/action/SandwichGameScene.ts
  src/game/scenes/action/SpamGameScene.ts
  src/game/scenes/index.ts
  src/game/scenes/waiting/ElevatorFirstGameScene.ts
  src/game/scenes/waiting/ElevatorSecondGameScene.ts
  src/store/GameStore.ts
  src/utils/constants.ts
  src/utils/enums.ts
  src/utils/functions.ts
  src/utils/game.ts
  src/utils/interfaces.ts
  src/utils/types.ts
Labels: dev, minigame, refacto

#27 Update/minigame spam
  public/static/assets/sprites/animations.json
  public/static/assets/sprites/pack.json
  public/static/assets/sprites/spam-game/gambling.png
  public/static/assets/sprites/spam-game/hair.png
  public/static/assets/sprites/spam-game/magic-bottle.png
  public/static/assets/sprites/spam-game/muscles.png
  public/static/assets/sprites/spam-game/pizza.png
  public/static/assets/sprites/spam-game/play.png
  public/static/assets/sprites/spam-game/sold.png
  public/static/assets/sprites/spam-game/sp_1.png
  public/static/assets/sprites/spam-game/sp_10_1.png
  public/static/assets/sprites/spam-game/sp_10_2.png
  public/static/assets/sprites/spam-game/sp_2.png
  public/static/assets/sprites/spam-game/sp_2_1.png
  public/static/assets/sprites/spam-game/sp_2_2.png
  public/static/assets/sprites/spam-game/sp_3.png
  public/static/assets/sprites/spam-game/sp_3_1.png
  public/static/assets/sprites/spam-game/sp_3_2.png
  public/static/assets/sprites/spam-game/sp_4_1.png
  public/static/assets/sprites/spam-game/sp_4_3.png
  public/static/assets/sprites/spam-game/sp_5_1.png
  public/static/assets/sprites/spam-game/sp_5_2.png
  public/static/assets/sprites/spam-game/sp_6_1.png
  public/static/assets/sprites/spam-game/sp_6_2.png
  public/static/assets/sprites/spam-game/sp_7_1.png
  public/static/assets/sprites/spam-game/sp_7_2.png
  public/static/assets/sprites/spam-game/sp_8_1.png
  public/static/assets/sprites/spam-game/sp_8_2.png
  public/static/assets/sprites/spam-game/sp_8_3.png
  public/static/assets/sprites/spam-game/sp_8_4.png
  public/static/assets/sprites/spam-game/sp_8_5.png
  public/static/assets/sprites/spam-game/sp_9_1.png
  public/static/assets/sprites/spam-game/sp_9_2.png
  public/static/assets/sprites/spam-game/sp_9_3.png
  public/static/assets/sprites/spam-game/sp_9_4.png
  public/static/assets/sprites/spam-game/tooth.png
  public/static/assets/sprites/spam-game/yo.png
  src/game/scenes/action/SpamGameScene.ts
Labels: dev, enhancement

#26 Toki run animation sprite updated
  public/static/assets/sprites/animations.json
  public/static/assets/sprites/pack.json
  public/static/assets/sprites/sandwich-game/btn_left_off.png
  public/static/assets/sprites/sandwich-game/btn_left_on.png
  public/static/assets/sprites/sandwich-game/btn_right_off.png
  public/static/assets/sprites/sandwich-game/btn_right_on.png
  public/static/assets/sprites/sandwich-game/toki_run_255_480.png
  src/game/scenes/action/SandwichGameScene.ts
Labels: dev, enhancement

#28 Update/minigame sandwich
  public/static/assets/sprites/animations.json
  src/game/scenes/action/SandwichGameScene.ts
Labels: dev, enhancement

#30 Fix disable controls on win event
  src/game/scenes/action/SandwichGameScene.ts
Labels: dev, fix

#31 [HOTFIX] - Sandwich game ending
  src/game/scenes/action/SandwichGameScene.ts
Labels: dev, fix

#32 [FEAT] - Post minigame
  public/static/assets/sprites/animations.json
  public/static/assets/sprites/pack.json
  src/assets/sprites/post-minigame/life_1_285_270.png
  src/assets/sprites/post-minigame/life_2_285_270.png
  src/assets/sprites/post-minigame/life_3_285_270.png
  src/assets/styles/components/_game-ui.scss
  src/components/Game.tsx
  src/components/ui/GameUI.tsx
  src/components/ui/PostMinigameUI.tsx
  src/components/ui/Spritesheet.tsx
  src/components/ui/games/RemainingTime.tsx
  src/components/ui/post-minigame/LivesList.tsx
  src/game/manager/GameManager.ts
  src/game/scenes/BootScene.ts
  src/game/scenes/MinigameScene.ts
  src/game/scenes/PostMinigameScene.ts
  src/game/scenes/action/PasswordGameScene.ts
  src/game/scenes/action/SandwichGameScene.ts
  src/game/scenes/action/SpamGameScene.ts
  src/store/GameStore.ts
  src/utils/anims.ts
  src/utils/functions.ts
Labels: dev, enhancement, ui

#34 [FIX] Production assets
  public/index.html
  public/static/assets/sprites/pack.json
  public/static/assets/sprites/password-game/mdp_keyboard_1.png
  public/static/assets/sprites/password-game/mdp_keyboard_1_hover.png
  public/static/assets/sprites/password-game/mdp_keyboard_2.png
  public/static/assets/sprites/password-game/mdp_keyboard_2_hover.png
  public/static/assets/sprites/password-game/mdp_keyboard_3.png
  public/static/assets/sprites/password-game/mdp_keyboard_3_hover.png
  public/static/assets/sprites/password-game/mdp_keyboard_4.png
  public/static/assets/sprites/password-game/mdp_keyboard_4_hover.png
  public/static/assets/sprites/password-game/mdp_keyboard_5.png
  public/static/assets/sprites/password-game/mdp_keyboard_5_hover.png
  public/static/assets/sprites/password-game/mdp_keyboard_6.png
  public/static/assets/sprites/password-game/mdp_keyboard_6_hover.png
  public/static/assets/sprites/password-game/mdp_paw.png
  public/static/assets/sprites/password-game/mdp_screen_1.png
  public/static/assets/sprites/password-game/mdp_screen_2.png
  public/static/assets/sprites/password-game/mdp_star.png
  public/static/assets/sprites/password-game/mdp_symbol_1.png
  public/static/assets/sprites/password-game/mdp_symbol_2.png
  public/static/assets/sprites/password-game/mdp_symbol_3.png
  public/static/assets/sprites/password-game/mdp_symbol_4.png
  public/static/assets/sprites/password-game/mdp_symbol_5.png
  public/static/assets/sprites/password-game/mdp_symbol_6.png
  public/static/assets/sprites/password-game/spritesheets/mdp_nope_870x975.png
  public/static/assets/sprites/password-game/spritesheets/mdp_paper_915x1215.png
  public/static/assets/sprites/password-game/spritesheets/mdp_valid_870x975.png
  public/static/assets/sprites/post-minigame/life_1_285_270.png
  public/static/assets/sprites/post-minigame/life_2_285_270.png
  public/static/assets/sprites/post-minigame/life_3_285_270.png
  public/static/assets/sprites/spam-game/close.png
  public/static/assets/sprites/spam-game/close_active.png
  src/assets/images/icons/debug.png
  src/components/ui/debug/GameDebugToggleButton.tsx
  src/game/scenes/BaseScene.ts
  src/game/scenes/BootScene.ts
  src/game/scenes/action/SandwichGameScene.ts
  src/game/scenes/action/SpamGameScene.ts
  src/index.tsx
Labels: dev, fix

#35 [DEBUG] - Mute sound button
  src/components/ui/debug/GameDebugButtonsToolbar.tsx
  src/components/ui/debug/GameDebugToggleSoundsButton.tsx
  src/game/manager/AudioManager.ts
  src/store/GameStore.ts
Labels: debug, dev, enhancement

#38 [FIX] - Réduction spritesheets post-minigame
  src/assets/sprites/post-minigame/life_1_285_270.png
  src/assets/sprites/post-minigame/life_2_285_270.png
  src/assets/sprites/post-minigame/life_3_285_270.png
  src/components/ui/PostMinigameUI.tsx
  src/components/ui/post-minigame/LivesList.tsx
Labels: dev, fix, ui

#39 [FIX of fix 🙄] - Forgotten spritesheet
  public/static/assets/sprites/post-minigame/life_1_285_270.png
  public/static/assets/sprites/post-minigame/life_2_285_270.png
  public/static/assets/sprites/post-minigame/life_3_285_270.png
Labels: dev, fix, ui

#36 [FEAT] - Introduction
  src/App.tsx
  src/assets/styles/app.scss
  src/components/Game.tsx
  src/components/Introduction.tsx
  src/components/ui/debug/GameDebugToggleButton.tsx
  src/game/manager/GameManager.ts
  src/game/scenes/BaseScene.ts
  src/game/scenes/BootScene.ts
  src/index.tsx
  src/store/GameStore.ts
  src/utils/game.ts
Labels: dev, enhancement, ui

#40 [FEAT] Minigame guideline
  public/static/assets/sounds/guideline_appear.ogg
  public/static/assets/sounds/guideline_leave.ogg
  public/static/assets/sounds/yeah.ogg
  public/static/assets/sprites/pack.json
  src/components/ui/MinigameGuideline.tsx
  src/components/ui/MinigameUI.tsx
  src/components/ui/debug/GameDebugMinigamePicker.tsx
  src/game/manager/GameManager.ts
  src/game/manager/MinigameManager.ts
  src/game/objects/Spam.ts
  src/game/scenes/MinigameScene.ts
  src/game/scenes/action/PasswordGameScene.ts
  src/game/scenes/action/SandwichGameScene.ts
  src/game/scenes/action/SpamGameScene.ts
  src/utils/interfaces.ts
  src/utils/keyframes.ts
Labels: dev, enhancement, sounds, ui

#41 [FEAT] Incremental difficulty
  src/components/ui/ValidatableInput.tsx
  src/components/ui/debug/DebugContainer.tsx
  src/components/ui/debug/GameDebugConfigPanel.tsx
  src/game/manager/AudioManager.ts
  src/game/objects/password-game/ComputerPasswordScreen.ts
  src/game/scenes/MinigameScene.ts
  src/game/scenes/PostMinigameScene.ts
  src/game/scenes/action/PasswordGameScene.ts
  src/game/scenes/action/SpamGameScene.ts
  src/store/GameStore.ts
  src/utils/interfaces.ts
Labels: dev, enhancement, refacto

#37 Game/elevator game
  public/static/assets/sprites/animations.json
  public/static/assets/sprites/elevator-game/bras_elevator_240_345.png
  public/static/assets/sprites/elevator-game/case_blase_elevator.png
  public/static/assets/sprites/elevator-game/case_call_elevator_450_480.png
  public/static/assets/sprites/elevator-game/elevator_bkg_335_600.png
  public/static/assets/sprites/elevator-game/floors_175_85.png
  public/static/assets/sprites/elevator-game/goutte_blase_45_135.png
  public/static/assets/sprites/elevator-game/music_note_195_120.png
  public/static/assets/sprites/elevator-game/toki_irrite_315_1185.png
  public/static/assets/sprites/elevator-game/toki_whistle_300_1185.png
  public/static/assets/sprites/pack.json
  src/game/manager/MinigameManager.ts
  src/game/scenes/action/ElevatorGameScene.ts
  src/game/scenes/index.ts
  src/utils/constants.ts
  src/utils/game.ts
Labels: dev, enhancement, minigame

#42 Games/minigame traffic
  public/static/assets/sprites/animations.json
  public/static/assets/sprites/pack.json
  public/static/assets/sprites/spam-game/close.png
  public/static/assets/sprites/spam-game/close_active.png
  public/static/assets/sprites/traffic-game/horn_on.png
  public/static/assets/sprites/traffic-game/rage_bar.png
  public/static/assets/sprites/traffic-game/rage_cursor.png
  public/static/assets/sprites/traffic-game/road.png
  public/static/assets/sprites/traffic-game/spritesheets/traffic_blue_car_570_435.png
  public/static/assets/sprites/traffic-game/spritesheets/traffic_cars_01_1395_540.png
  public/static/assets/sprites/traffic-game/spritesheets/traffic_cars_02_930_450.png
  public/static/assets/sprites/traffic-game/spritesheets/traffic_cars_03_990_540.png
  public/static/assets/sprites/traffic-game/spritesheets/traffic_cars_04_1200_495.png
  public/static/assets/sprites/traffic-game/spritesheets/traffic_horn_465_375.png
  public/static/assets/sprites/traffic-game/spritesheets/traffic_toki_570_540.png
  src/game/manager/MinigameManager.ts
  src/game/objects/traffic-game/Car.ts
  src/game/objects/traffic-game/CarLine.ts
  src/game/objects/traffic-game/CarsContainer.ts
  src/game/objects/traffic-game/RoadsContainer.ts
  src/game/scenes/action/TrafficGameScene.ts
  src/game/scenes/index.ts
  src/utils/constants.ts
  src/utils/game.ts
Labels: bug, dev, enhancement, minigame, refacto

#43 [FEAT] - Pause
  public/index.html
  src/assets/sprites/pause/cigarette_150_110.png
  src/assets/sprites/pause/mug_85_115.png
  src/assets/sprites/pause/pause_bg.png
  src/assets/sprites/pause/warning_sign.png
  src/assets/styles/bootstrap.scss
  src/assets/styles/components/_modals.scss
  src/assets/styles/modules/_colors.scss
  src/components/Game.tsx
  src/components/ui/GameButton.tsx
  src/components/ui/GameUI.tsx
  src/components/ui/MinigameGuideline.tsx
  src/components/ui/MinigameUI.tsx
  src/components/ui/ModalsContainer.tsx
  src/components/ui/debug/GameDebugTogglePauseButton.tsx
  src/components/ui/games/GamePauseButton.tsx
  src/components/ui/games/MinigameToolbar.tsx
  src/components/ui/games/RemainingTime.tsx
  src/components/ui/modals/PauseModal.tsx
  src/components/ui/modals/WarningSign.tsx
  src/game/manager/AudioManager.ts
  src/game/manager/GameManager.ts
  src/store/GameDebugStore.ts
  src/store/GameStore.ts
  src/utils/colors.ts
  src/utils/css.ts
  src/utils/game.ts
  src/utils/hooks.ts
  src/utils/keyframes.ts
Labels: dev, enhancement, ui

#44 [FIX] Pause button and guideline workflow
  src/components/ui/MinigameGuideline.tsx
  src/components/ui/games/GamePauseButton.tsx
  src/store/GameStore.ts
  src/utils/hooks.ts
Labels: dev, fix, ui

#45 Fix/sandwich game
  public/static/assets/sprites/sandwich-game/sandwich_plan_building.png
  public/static/assets/sprites/sandwich-game/sandwich_plan_ground.png
  public/static/assets/sprites/sandwich-game/sandwich_plan_landscape.png
  public/static/assets/sprites/sandwich-game/sandwich_plan_sky.png
  public/static/assets/sprites/sandwich-game/sandwich_plan_street-lights.png
  src/game/scenes/action/SandwichGameScene.ts
Labels: fix

#46 [FEAT] - Leaderboards
  .env
  package.json
  src/assets/images/icons/btn_facebook.png
  src/assets/images/icons/btn_twitter.png
  src/client/HFLApiClient.ts
  src/components/ui/GameButton.tsx
  src/components/ui/GameUI.tsx
  src/components/ui/LeaderboardsUI.tsx
  src/components/ui/MinigameUI.tsx
  src/components/ui/debug/GameDebugConfigPanel.tsx
  src/components/ui/leaderboards/LeaderboardsEntry.tsx
  src/components/ui/leaderboards/LeaderboardsTable.tsx
  src/components/ui/leaderboards/LeaderboardsUsernameInput.tsx
  src/components/ui/leaderboards/LeaderboardsUsernameInputBlock.tsx
  src/game/manager/GameManager.ts
  src/game/scenes/LeaderboardsScene.ts
  src/game/scenes/PostMinigameScene.ts
  src/game/scenes/index.ts
  src/store/GameStore.ts
  src/store/LeaderboardsStore.ts
  src/utils/constants.ts
  src/utils/enums.ts
  src/utils/game.ts
  src/utils/keyframes.ts
  yarn.lock
Labels: dev, enhancement, ui

#48 Fix visual issue due to sprite size
  public/static/assets/sprites/pack.json
  public/static/assets/sprites/spam-game/yo.png
  public/static/assets/sprites/spam-game/yo_284_429.png
Labels: dev, fix

#47 Fix/traffic game
  public/static/assets/sprites/pack.json
  public/static/assets/sprites/traffic-game/horn_off.png
  public/static/assets/sprites/traffic-game/traffic_horn_on.png
  src/game/scenes/action/TrafficGameScene.ts
Labels: dev, enhancement, fix

#51 Fix yo animation size
  src/game/objects/Spam.ts
Labels: dev, fix

#52 Fix/sandwich game
  src/game/scenes/action/SandwichGameScene.ts
Labels: dev, fix

#54 Fix issues when game restart
  src/game/scenes/action/TrafficGameScene.ts
Labels: dev, fix
