Repository Liinkiing/harder-faster-loser, pull requests merged in 2019-02, with the labels that each got.

#58 Games/subway game
  public/static/assets/sprites/animations.json
  public/static/assets/sprites/pack.json
  public/static/assets/sprites/subway-game/spritesheets/subway_character_time_135x300.png
  public/static/assets/sprites/subway-game/spritesheets/subway_toki_run_120x315.png
  public/static/assets/sprites/subway-game/spritesheets/subway_toki_time_135x285.png
  public/static/assets/sprites/subway-game/spritesheets/subway_toki_win_240x330.png
  public/static/assets/sprites/subway-game/spritesheets/subway_train_door_660x360.png
  public/static/assets/sprites/subway-game/spritesheets/subway_train_inside_630x390.png
  public/static/assets/sprites/subway-game/subway_active_train.png
  public/static/assets/sprites/subway-game/subway_first_train.png
  public/static/assets/sprites/subway-game/subway_grey_square.png
  public/static/assets/sprites/subway-game/subway_last_train.png
  public/static/assets/sprites/subway-game/subway_railroad.png
  public/static/assets/sprites/subway-game/subway_train.png
  public/static/assets/sprites/subway-game/subway_yellow_border_square.png
  src/game/manager/MinigameManager.ts
  src/game/objects/subway-game/Wagon.ts
  src/game/scenes/BootScene.ts
  src/game/scenes/action/SubwayGameScene.ts
  src/game/scenes/index.ts
  src/store/GameStore.ts
  src/utils/constants.ts
  src/utils/game.ts
Labels: dev, enhancement, minigame

#59 Feat/deathscreen
  public/static/assets/sprites/animations.json
  public/static/assets/sprites/deathscreen/deathscreen_clouds_0.png
  public/static/assets/sprites/deathscreen/deathscreen_clouds_1.png
  public/static/assets/sprites/deathscreen/deathscreen_graveyard_background.png
  public/static/assets/sprites/deathscreen/deathscreen_stage_set_0.png
  public/static/assets/sprites/deathscreen/deathscreen_stage_set_1.png
  public/static/assets/sprites/deathscreen/deathscreen_tombstones.png
  public/static/assets/sprites/deathscreen/spritesheets/deathscreen_rain_67_120.png
  public/static/assets/sprites/pack.json
  src/assets/data.json
  src/components/ui/DeathscreenUI.tsx
  src/data.d.ts
  src/game/manager/DataManager.ts
  src/game/scenes/BaseScene.ts
  src/game/scenes/DeathscreenScene.ts
  src/utils/enums.ts
  src/utils/interfaces.ts
Labels: dev, enhancement

#56 [FEAT] - Splashscreen
  public/static/assets/sounds/clock.m4a
  public/static/assets/sounds/clock.mp3
  public/static/assets/sounds/clock.ogg
  public/static/assets/sounds/crack.m4a
  public/static/assets/sounds/crack.mp3
  public/static/assets/sounds/crack.ogg
  public/static/assets/sounds/falling.m4a
  public/static/assets/sounds/falling.mp3
  public/static/assets/sounds/falling.ogg
  public/static/assets/sounds/squash.m4a
  public/static/assets/sounds/squash.mp3
  public/static/assets/sounds/squash.ogg
  public/static/assets/sounds/wind.m4a
  public/static/assets/sounds/wind.mp3
  public/static/assets/sounds/wind.ogg
  public/static/assets/sprites/animations.json
  public/static/assets/sprites/pack.json
  public/static/assets/sprites/splashscreen/credits.png
  public/static/assets/sprites/splashscreen/spritesheets/splashscreen_01_133_239.png
  public/static/assets/sprites/splashscreen/spritesheets/splashscreen_02_133_239.png
  public/static/assets/sprites/splashscreen/spritesheets/tic_tac_133_239.png
  public/static/assets/sprites/splashscreen_animations.json
  src/components/Introduction.tsx
  src/components/ui/DeathscreenUI.tsx
  src/components/ui/SplashscreenUI.tsx
  src/game/manager/AudioManager.ts
  src/game/manager/GameManager.ts
  src/game/manager/MinigameManager.ts
  src/game/objects/Spam.ts
  src/game/scenes/BaseScene.ts
  src/game/scenes/BootScene.ts
  src/game/scenes/DeathscreenScene.ts
  src/game/scenes/HomescreenScene.ts
  src/game/scenes/MinigameScene.ts
  src/game/scenes/PostMinigameScene.ts
  src/game/scenes/SplashscreenScene.ts
  src/game/scenes/action/SubwayGameScene.ts
  src/store/GameStore.ts
  src/store/LeaderboardsStore.ts
  src/utils/enums.ts
Labels: dev, enhancement, sounds

#60 Update assets elevator 1:1 and add plant
  public/static/assets/sprites/elevator-game/bras_elevator_240_345.png
  public/static/assets/sprites/elevator-game/btn_ascenseur_16_23.png
  public/static/assets/sprites/elevator-game/case_blase_elevator.png
  public/static/assets/sprites/elevator-game/case_blase_elevator_31_32.png
  public/static/assets/sprites/elevator-game/case_call_elevator_30_32.png
  public/static/assets/sprites/elevator-game/case_call_elevator_450_480.png
  public/static/assets/sprites/elevator-game/elevator_bkg_335_600.png
  public/static/assets/sprites/elevator-game/elevator_bkg_67_120.png
  public/static/assets/sprites/elevator-game/floors_175_85.png
  public/static/assets/sprites/elevator-game/goutte_blase_3_9.png
  public/static/assets/sprites/elevator-game/goutte_blase_45_135.png
  public/static/assets/sprites/elevator-game/music_note_195_120.png
  public/static/assets/sprites/elevator-game/music_notes_13_8.png
  public/static/assets/sprites/elevator-game/niveauelevator_35_17.png
  public/static/assets/sprites/elevator-game/plante_19_38.png
  public/static/assets/sprites/elevator-game/toki_irrite_21_79.png
  public/static/assets/sprites/elevator-game/toki_irrite_315_1185.png
  public/static/assets/sprites/elevator-game/toki_whistle_20_79.png
  public/static/assets/sprites/elevator-game/toki_whistle_300_1185.png
  public/static/assets/sprites/pack.json
  src/game/scenes/action/ElevatorGameScene.ts
Labels: fix, ui

#61 [UPDATE] - Splashscreen
  public/static/assets/sprites/pack.json
  public/static/assets/sprites/splashscreen/spritesheets/loader_10_10.png
  public/static/assets/sprites/splashscreen_animations.json
  src/game/scenes/SplashscreenScene.ts
Labels: dev, ui

#64 [FIX] - Quit pause button
  src/components/ui/modals/PauseModal.tsx
  src/store/GameStore.ts
Labels: dev, fix, sounds, ui

#65 [FIX] - Sandwich game buttons
  src/game/scenes/action/SandwichGameScene.ts
Labels: dev, fix

#62 [FEAT] - Before game
  src/assets/sprites/btn_red.png
  src/components/Introduction.tsx
  src/components/ui/BigButton.tsx
Labels: dev, enhancement, ui

#63 [FEAT] - Introduction
  src/components/ui/AutoScroll.tsx
  src/components/ui/GameUI.tsx
  src/components/ui/IntroductionUI.tsx
  src/game/manager/GameManager.ts
  src/game/scenes/BaseScene.ts
  src/game/scenes/IntroductionScene.ts
  src/game/scenes/PostMinigameScene.ts
  src/game/scenes/SplashscreenScene.ts
  src/game/scenes/index.ts
  src/utils/constants.ts
  src/utils/enums.ts
  src/utils/game.ts
Labels: dev, enhancement, ui

#66 [UPDATE] - Scoring system
  package.json
  src/components/ui/LeaderboardsUI.tsx
  src/components/ui/PostMinigameUI.tsx
  src/components/ui/games/RemainingTime.tsx
  src/components/ui/leaderboards/LeaderboardsEntry.tsx
  src/components/ui/leaderboards/LeaderboardsTable.tsx
  src/game/scenes/MinigameScene.ts
  src/store/GameStore.ts
  src/store/LeaderboardsStore.ts
  src/utils/enums.ts
  yarn.lock
Labels: dev, enhancement, fix

#68 Fix/subway game
  src/game/scenes/action/SubwayGameScene.ts
  src/utils/colors.ts
Labels: dev, fix, minigame, refacto

#70 - Fixed class variables reset
  src/game/scenes/action/SubwayGameScene.ts
Labels: dev, fix

#71 deleting a recalcitrant comment
  package-lock.json
  src/game/scenes/action/ElevatorGameScene.ts
Labels: fix

#67 Update assets/sandwich game
  public/static/assets/sprites/pack.json
  public/static/assets/sprites/sandwich-game/btn_left_off.png
  public/static/assets/sprites/sandwich-game/btn_left_on.png
  public/static/assets/sprites/sandwich-game/btn_right_off.png
  public/static/assets/sprites/sandwich-game/btn_right_on.png
  public/static/assets/sprites/sandwich-game/sandwich_flying_39_36.png
  public/static/assets/sprites/sandwich-game/sandwich_flying_585_540.png
  public/static/assets/sprites/sandwich-game/sandwich_plan_building.png
  public/static/assets/sprites/sandwich-game/sandwich_plan_ciel.png
  public/static/assets/sprites/sandwich-game/sandwich_plan_ground.png
  public/static/assets/sprites/sandwich-game/sandwich_plan_landscape.png
  public/static/assets/sprites/sandwich-game/sandwich_plan_sky.png
  public/static/assets/sprites/sandwich-game/sandwich_plan_street-lights.png
  public/static/assets/sprites/sandwich-game/toki_run_17_32.png
  public/static/assets/sprites/sandwich-game/toki_run_255_480.png
  public/static/assets/sprites/sandwich-game/toki_win_26_57.png
  public/static/assets/sprites/sandwich-game/toki_win_390_855.png
  src/game/scenes/action/SandwichGameScene.ts
Labels: fix, ui

#69 Update size of assets and scale
  public/static/assets/sprites/pack.json
  public/static/assets/sprites/traffic-game/horn_off.png
  public/static/assets/sprites/traffic-game/horn_on.png
  public/static/assets/sprites/traffic-game/rage_bar.png
  public/static/assets/sprites/traffic-game/rage_cursor.png
  public/static/assets/sprites/traffic-game/road.png
  public/static/assets/sprites/traffic-game/spritesheets/traffic_blue_car_38_29.png
  public/static/assets/sprites/traffic-game/spritesheets/traffic_blue_car_570_435.png
  public/static/assets/sprites/traffic-game/spritesheets/traffic_cars_01_1395_540.png
  public/static/assets/sprites/traffic-game/spritesheets/traffic_cars_01_93_36.png
  public/static/assets/sprites/traffic-game/spritesheets/traffic_cars_02_62_30.png
  public/static/assets/sprites/traffic-game/spritesheets/traffic_cars_02_930_450.png
  public/static/assets/sprites/traffic-game/spritesheets/traffic_cars_03_66_36.png
  public/static/assets/sprites/traffic-game/spritesheets/traffic_cars_03_990_540.png
  public/static/assets/sprites/traffic-game/spritesheets/traffic_cars_04_1200_495.png
  public/static/assets/sprites/traffic-game/spritesheets/traffic_cars_04_80_33.png
  public/static/assets/sprites/traffic-game/spritesheets/traffic_horn_465_375.png
  public/static/assets/sprites/traffic-game/spritesheets/traffic_klaxon_sound_31_25.png
  public/static/assets/sprites/traffic-game/spritesheets/traffic_toki_38_36.png
  public/static/assets/sprites/traffic-game/spritesheets/traffic_toki_570_540.png
  public/static/assets/sprites/traffic-game/traffic_horn_on.png
  src/game/objects/traffic-game/Car.ts
  src/game/objects/traffic-game/CarsContainer.ts
  src/game/objects/traffic-game/RoadsContainer.ts
  src/game/scenes/action/TrafficGameScene.ts
Labels: fix, ui

#72 Update/deathscreen
  public/static/assets/sprites/deathscreen/deathscreen_empty_tombstone.png
  public/static/assets/sprites/pack.json
  src/assets/data.json
  src/components/ui/DeathscreenUI.tsx
  src/game/scenes/DeathscreenScene.ts
Labels: dev, enhancement, fix, refacto

#73 [FEAT] - Action indicators
  public/static/assets/sprites/action-indicators/hand_16_23.png
  public/static/assets/sprites/action-indicators/shake_34_25.png
  public/static/assets/sprites/animations.json
  public/static/assets/sprites/pack.json
  src/game/scenes/HomescreenScene.ts
  src/game/scenes/MinigameScene.ts
  src/game/scenes/action/ElevatorGameScene.ts
  src/game/scenes/action/TrafficGameScene.ts
Labels: dev, enhancement, ui

#75 [FIX] - Subway game error on game end
  src/game/scenes/action/SubwayGameScene.ts
Labels: dev, fix

#76 [FEAT] - Haptic feedback
  src/components/GameDebug.tsx
  src/components/ui/BigButton.tsx
  src/components/ui/GameButton.tsx
  src/components/ui/debug/GameDebugSettingsPanel.tsx
  src/components/ui/games/GamePauseButton.tsx
  src/game/manager/AudioManager.ts
  src/game/manager/GameManager.ts
  src/game/objects/Spam.ts
  src/game/objects/password-game/KeyboardPasswordButton.ts
  src/game/scenes/action/ElevatorGameScene.ts
  src/game/scenes/action/SandwichGameScene.ts
  src/game/scenes/action/TrafficGameScene.ts
  src/store/GameStore.ts
  src/utils/interfaces.ts
Labels: debug, dev, enhancement, sounds

#80 [FIX] - Safari bugs
  src/components/ui/GameButton.tsx
  src/components/ui/modals/SettingsModal.tsx
  src/game/manager/GameManager.ts
Labels: dev, fix

#81 Update/responsive
  src/components/ui/DeathscreenUI.tsx
  src/components/ui/IntroductionUI.tsx
  src/components/ui/MinigameGuideline.tsx
  src/components/ui/modals/SettingsModal.tsx
  src/game/scenes/DeathscreenScene.ts
  src/game/scenes/action/SubwayGameScene.ts
  src/game/scenes/action/TrafficGameScene.ts
Labels: dev, enhancement

#82 - Fix broken styles modal
  src/components/ui/modals/SettingsModal.tsx
Labels: dev, fix

#85 [FIX] - Score input vibration
  src/components/ui/BigButton.tsx
  src/components/ui/GameButton.tsx
  src/components/ui/games/GamePauseButton.tsx
  src/components/ui/leaderboards/LeaderboardsUsernameInputBlock.tsx
  src/utils/constants.ts
Labels: dev, fix

#86 [FEAT] - Notifications
  public/index.html
  public/static/assets/sprites/pack.json
  src/App.tsx
  src/assets/styles/app.scss
  src/components/ui/notifications/Notification.tsx
  src/components/ui/notifications/NotificationsContainer.tsx
  src/registerServiceWorker.ts
  src/utils/enums.ts
  src/utils/functions.ts
  src/utils/hooks.ts
  src/utils/keyframes.ts
Labels: dev, enhancement, ui

#87 [UPDATE] Deathscreen
  public/static/assets/sounds/rain.m4a
  public/static/assets/sounds/rain.mp3
  public/static/assets/sounds/rain.ogg
  public/static/assets/sounds/thunder.m4a
  public/static/assets/sounds/thunder.mp3
  public/static/assets/sounds/thunder.ogg
  public/static/assets/sprites/deathscreen/deathscreen_stage_set_0.png
  public/static/assets/sprites/deathscreen/deathscreen_stage_set_1.png
  public/static/assets/sprites/pack.json
  src/assets/data.json
  src/components/ui/DeathscreenUI.tsx
  src/game/manager/DataManager.ts
  src/game/scenes/DeathscreenScene.ts
  src/utils/enums.ts
Labels: dev, enhancement, refacto, sounds

#84 [FEAT] - Randomize minigame's background color
  src/game/scenes/MinigameScene.ts
  src/game/scenes/PostMinigameScene.ts
  src/game/scenes/action/ElevatorGameScene.ts
  src/game/scenes/action/PasswordGameScene.ts
  src/game/scenes/action/SandwichGameScene.ts
  src/game/scenes/action/SpamGameScene.ts
  src/game/scenes/action/SubwayGameScene.ts
  src/store/GameStore.ts
Labels: dev, enhancement, minigame, ui

#89 [FIX] - Randomize color minigame
  src/game/scenes/action/ElevatorGameScene.ts
  src/game/scenes/action/PasswordGameScene.ts
  src/game/scenes/action/SpamGameScene.ts
  src/game/scenes/action/SubwayGameScene.ts
Labels: dev, fix

#92 - Update sprite size 1:1
  public/static/assets/sprites/pack.json
  public/static/assets/sprites/password-game/spritesheets/mdp_nope_58x65.png
  public/static/assets/sprites/password-game/spritesheets/mdp_nope_870x975.png
  public/static/assets/sprites/password-game/spritesheets/mdp_paper_60x81.png
  public/static/assets/sprites/password-game/spritesheets/mdp_paper_915x1215.png
  public/static/assets/sprites/password-game/spritesheets/mdp_valid_58x65.png
  public/static/assets/sprites/password-game/spritesheets/mdp_valid_870x975.png
  src/game/scenes/action/PasswordGameScene.ts
Labels: dev, enhancement, minigame

#91 Update/game levels
  src/game/scenes/action/ElevatorGameScene.ts
  src/game/scenes/action/SandwichGameScene.ts
  src/game/scenes/action/SpamGameScene.ts
  src/game/scenes/action/TrafficGameScene.ts
Labels: dev, minigame, refacto

#90 Update/subway game
  public/static/assets/sprites/pack.json
  public/static/assets/sprites/subway-game/spritesheets/subway_character_time_135x300.png
  public/static/assets/sprites/subway-game/spritesheets/subway_character_time_9x20.png
  public/static/assets/sprites/subway-game/spritesheets/subway_toki_run_120x315.png
  public/static/assets/sprites/subway-game/spritesheets/subway_toki_run_8x21.png
  public/static/assets/sprites/subway-game/spritesheets/subway_toki_time_135x285.png
  public/static/assets/sprites/subway-game/spritesheets/subway_toki_time_9x20.png
  public/static/assets/sprites/subway-game/spritesheets/subway_toki_win_16x22.png
  public/static/assets/sprites/subway-game/spritesheets/subway_toki_win_240x330.png
  public/static/assets/sprites/subway-game/spritesheets/subway_train_door_44x24.png
  public/static/assets/sprites/subway-game/spritesheets/subway_train_inside_42x26.png
  src/game/scenes/action/SubwayGameScene.ts
Labels: dev, enhancement, minigame

#94 [UPDATE] Taille des sprites du jeu des spams
  public/static/assets/sprites/pack.json
  public/static/assets/sprites/spam-game/gambling.png
  public/static/assets/sprites/spam-game/hair.png
  public/static/assets/sprites/spam-game/magic-bottle.png
  public/static/assets/sprites/spam-game/muscles.png
  public/static/assets/sprites/spam-game/pizza.png
  public/static/assets/sprites/spam-game/play.png
  public/static/assets/sprites/spam-game/sexy.png
  public/static/assets/sprites/spam-game/sold.png
  public/static/assets/sprites/spam-game/spritesheets/sp_gambling_61_68.png
  public/static/assets/sprites/spam-game/spritesheets/sp_hair_53_51.png
  public/static/assets/sprites/spam-game/spritesheets/sp_magic_bottle_57_61.png
  public/static/assets/sprites/spam-game/spritesheets/sp_muscles_53_68.png
  public/static/assets/sprites/spam-game/spritesheets/sp_pizza_57_86.png
  public/static/assets/sprites/spam-game/spritesheets/sp_play_53_40.png
  public/static/assets/sprites/spam-game/spritesheets/sp_sexy_57_86.png
  public/static/assets/sprites/spam-game/spritesheets/sp_sold_53_68.png
  public/static/assets/sprites/spam-game/spritesheets/sp_tooth_53_68.png
  public/static/assets/sprites/spam-game/spritesheets/sp_yo_57_86.png
  public/static/assets/sprites/spam-game/tooth.png
  public/static/assets/sprites/spam-game/yo_284_429.png
  src/game/objects/Spam.ts
Labels: dev, enhancement, minigame

#95 Fix/deathscreen
  src/components/ui/DeathscreenUI.tsx
  src/game/scenes/DeathscreenScene.ts
Labels: dev, fix

#96 [FIX] Subway game
  public/static/assets/sprites/animations.json
  src/game/scenes/action/SubwayGameScene.ts
Labels: debug, dev, fix, minigame, refacto

#97 [FIX] Traffic game
  src/game/scenes/action/TrafficGameScene.ts
Labels: dev, fix

#100 Improve minigame guide
  src/components/ui/MinigameGuideline.tsx
  src/game/scenes/action/ElevatorGameScene.ts
  src/game/scenes/action/PasswordGameScene.ts
  src/game/scenes/action/SandwichGameScene.ts
  src/game/scenes/action/SpamGameScene.ts
  src/game/scenes/action/SubwayGameScene.ts
  src/game/scenes/action/TrafficGameScene.ts
Labels: fix

#93 [SOUNDS] - Subway game
  public/static/assets/sounds/subway_doors_closing.m4a
  public/static/assets/sounds/subway_doors_closing.mp3
  public/static/assets/sounds/subway_doors_closing.ogg
  public/static/assets/sounds/subway_doors_opening.m4a
  public/static/assets/sounds/subway_doors_opening.mp3
  public/static/assets/sounds/subway_doors_opening.ogg
  public/static/assets/sounds/train.m4a
  public/static/assets/sounds/train.mp3
  public/static/assets/sounds/train.ogg
  public/static/assets/sprites/pack.json
  src/components/ui/MinigameGuideline.tsx
  src/game/scenes/action/SubwayGameScene.ts
Labels: dev, minigame, sounds

#98 Add responsive splashscreen
  public/static/assets/sprites/pack.json
  public/static/assets/sprites/splashscreen/spritesheets/splashscreen_01_133_239.png
  public/static/assets/sprites/splashscreen/spritesheets/splashscreen_02_133_239.png
  public/static/assets/sprites/splashscreen/spritesheets/splashscreen_ground.png
  src/game/scenes/SplashscreenScene.ts
Labels: dev, fix, ui

#102 [FEAT] - Toggle sounds
  src/assets/images/icons/picto_no_sound.png
  src/components/ui/SoundPicto.tsx
  src/components/ui/modals/SettingsModal.tsx
  src/store/GameStore.ts
Labels: dev, enhancement, sounds, ui

#103 Revert "Add responsive splashscreen"
  public/static/assets/sprites/pack.json
  public/static/assets/sprites/splashscreen/spritesheets/splashscreen_01_133_239.png
  public/static/assets/sprites/splashscreen/spritesheets/splashscreen_02_133_239.png
  public/static/assets/sprites/splashscreen/spritesheets/splashscreen_ground.png
  src/game/scenes/SplashscreenScene.ts
Labels: dev, fix

#106 - Fix padding-top deathscreen
  src/components/ui/DeathscreenUI.tsx
Labels: dev, fix, ui

#105 [UPDATE] - Subway sounds
  public/static/assets/sounds/subway_doors.m4a
  public/static/assets/sounds/subway_doors.mp3
  public/static/assets/sounds/subway_doors.ogg
  public/static/assets/sprites/pack.json
  src/game/scenes/action/SubwayGameScene.ts
Labels: dev, sounds

#101 [FEAT] - Desktop warning
  src/App.tsx
  src/assets/sprites/hfl_desktop_anim_48x133.png
  src/components/DesktopWarning.tsx
  src/game/manager/GameManager.ts
  src/game/scenes/BootScene.ts
  src/registerServiceWorker.ts
Labels: dev, enhancement, ui

#104 - Changed text in introduction
  src/assets/sprites/introduction/intro_toki_running.gif
  src/components/Introduction.tsx
  src/components/ui/DeathscreenUI.tsx
  src/components/ui/IntroductionUI.tsx
  src/game/scenes/DeathscreenScene.ts
Labels: ui

#107 - Quick fix data
  src/assets/data.json
  src/components/Introduction.tsx
Labels: dev, ui
